### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by razy69** [NiclasvanEyk/blob-ui#1]
Hi, really nice UI ! i love it. It's not an issue, but just a suggestion.
Is it possible to add a margin top to the first line of the file ?

Accorded to me, tabs and the first line are too nearly.

Sorry for my bad english.

**Comment by NiclasvanEyk** [comment]
Hi, I'm glad you like it.
Unfortunately, adding a margin-top only to the first line of the file is pretty difficult, because each line is positioned absolute. 
Adding `margin-top` to the line itself would do nothing, so you would have to add your margin to the `top` value of each line, which is pretty difficult. Alternatively you could add a `margin-top` to the container, but then the whole container is moved down a bit.

If you want to try the second method, just add this to your styles.less (settings->themes->the link under the heading):
```less
atom-text-editor::shadow{
  .editor-contents--private{
    margin-top: 20px;
  }
}
```

I hope this could help you.

**Comment by razy69** [comment]
Oh thanks this method works very well ! Your ui is very awesome :D
